### ISSUE TITLE
 On Parent categories offer is not working

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/upsell-order-bump-offer-for-woocommerce#1]
Bug name:when we select parent categories for applying offer then it will show no any offer  
Area Path: frontend>checkout
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:-when we select parent categories for applying offer then we will show no any offer in that categories but if we apply in subcategories then it will show offer

**Comment by ced-ashutoshv** [comment]
Implemented!

**Comment by abhayp-cedcoss** [comment]
okay
