### ISSUE TITLE
Invalid CSS: /admin/css/upsell-order-bump-offer-for-woocommerce-admin.css

### ISSUE THREAD

**Issue by sacvalleytech** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#10]
It appears you have some minor syntax errors in the CSS file ` /admin/css/upsell-order-bump-offer-for-woocommerce-admin.css`

Line 1395 `  vertical-align: middle;"` (errant double quote on end of line)
Line 1813: missing closing curly bracket for `@media only screen and (max-width:782px) `

**Comment by MakeWebBetter** [comment]
@sacvalleytech you can create a pull request will test and if your patch seems correct then will merge that.

**Comment by MohdFaisalAliKhan-Cedcoss** [comment]
Let me know if this front-end issue still occurs.

**Comment by MohdFaisalAliKhan-Cedcoss** [comment]
RESOLVED
