### ISSUE TITLE
Getting notice above template "Could not generate the Unqiue ID for this Order Bump"

### ISSUE THREAD

**Issue by kavya1515** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#19]
![screenshot-localhost_10019-2021 05 27-16_49_19](https://user-images.githubusercontent.com/63343498/119817510-b2c91480-bf0b-11eb-89ed-b4b4e6bb8c16.png)

**Comment by MohdFaisalAliKhan-Cedcoss** [comment]
Resolved
