### ISSUE TITLE
click on the offer then loader is continuously loaded but page is loaded after we refresh the page

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/upsell-order-bump-offer-for-woocommerce#2]
Bug name:click on the offer then loader continuously loaded 
Area Path: frontend>my account page
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:-when we login with the admin and offer product on checkout page then it will not added until we will not refresh the page
![screenshot-192 168 1 184-2019 09 04-16_16_55](https://user-images.githubusercontent.com/48902379/64410463-b8802600-d0a8-11e9-98f4-ea0973debd77.png)
![screenshot-192 168 1 184-2019 09 04-16_20_57](https://user-images.githubusercontent.com/48902379/64410534-e06f8980-d0a8-11e9-9816-2170f727ffb7.png)

**Comment by ced-ashutoshv** [comment]
No such issue.
