### ISSUE TITLE
Designing-Issue In Responsive mode Admin Panel Order Bump > Order Bumps & Settings > Save Order Bump > Offer Price/Discount dropdown and input field have different width

### ISSUE THREAD

**Issue by kavya1515** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#21]

**Comment by anmolui** [comment]
https://www.awesomescreenshot.com/image/8871753?key=4e7da4412212396f862a08ed019c0be6
Resolved

**Comment by MohdFaisalAliKhan-Cedcoss** [comment]
![image](https://user-images.githubusercontent.com/76722886/120444414-391aa600-c3a5-11eb-8054-b513a0b4ec67.png)
