### ISSUE TITLE
issue with the total price after applying coupon

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#23]
wp version: 5.8
wc version: 5.5.2
version: v1.4.3
path: checkout page
description: there is difference in total after applying coupon of 20% off.
![coupon 2021 07 27-14_14_19](https://user-images.githubusercontent.com/86113814/127124895-9bcce57b-60c7-4051-81b6-c97c168e673e.png)

**Comment by MohdFaisalAliKhan-Cedcoss** [comment]
Resolved
