### ISSUE TITLE
order bump not working when offer product is a variable product. please watch video

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#24]
wp version: 5.8
wc version: 5.5.2
version: 1.4.3
path: checkout page
description: when we select variable product as a offer product, then in checkout page variable product is not responding.
[variable product 2021.07.27-14_32_08.zip](https://github.com/Makewebbetter/upsell-order-bump-offer-for-woocommerce/files/6884216/variable.product.2021.07.27-14_32_08.zip)

**Comment by MohdFaisalAliKhan-Cedcoss** [comment]
https://www.loom.com/share/eaf4b4a9491e4e40aadf4ece2dae8bdf
