### ISSUE TITLE
template, design and content box does not look appropriate in mobile

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#26]
wp version: 5.8
wc version: 5.5.2
version:1.4.3
path: save order bump>appearance
description: when we view save order bump in 'galaxy s5 mobile mode', then template and design boxes get in small size as compare to content box.
![apperance box 2021 07 27-15_57_27](https://user-images.githubusercontent.com/86113814/127141041-bb029b7d-1b46-46f2-8652-04aa250ed8dd.png)

**Comment by anmolui** [comment]
![image](https://user-images.githubusercontent.com/79319224/127725345-dcabfe32-f59d-4fdc-8e89-653648bb6202.png)
fixed
