### ISSUE TITLE
input box occurs when we select variable product in offer product or select fixed discount/fixed price

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#28]
os: window10
wp version:5.8
wc version: 5.6
version: 1.4.3
path: save bump offer
description: when we select variable product in offer product then input text box appear just below offer preview
![test box 2021 08 18-10_46_24](https://user-images.githubusercontent.com/86113814/129841345-e0a45326-c269-45a6-8f0c-5ee0d9f63d29.png)
![fixed price 2021 08 18-12_31_33](https://user-images.githubusercontent.com/86113814/129853117-4c22c550-7e65-4e78-b841-fed1b087a7e6.png)
![image](https://user-images.githubusercontent.com/86113814/129869150-84572f41-ebad-4993-8545-e3e7652cbeb6.png)

**Comment by MohdFaisalAliKhan-Cedcoss** [comment]
FIXED
