### ISSUE TITLE
when we we remove target product and still offer product in order

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/upsell-order-bump-offer-for-woocommerce#3]
when we add a target categories product and apply offer product then it will add into it
then we remove that categories product from the cart then  only offer product is in the cart  but it is in  original price (offer price is removed from the product)
and that offer product is also a target product then offer product is also shown on checkout when we add same that target product it will add with original price
and when we remove target product then it is remove all product as well target product

**Comment by ced-ashutoshv** [comment]
fixed
