### ISSUE TITLE
issue with offer price when we select discount%

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#30]
os: window10
wp version: 5.8
wc version: 5.6.0
version: 1.4.3
path: save order bump
description: first when we select no discount and then discount%, None appears in text box
![discount%-2021 08 24-12_07_54](https://user-images.githubusercontent.com/86113814/130569147-00f362dc-2c79-4bc5-ac7c-43e11ffa125a.png)
![image](https://user-images.githubusercontent.com/86113814/130574551-96b3120a-7320-490e-8ab6-dd0e9594f564.png)

**Comment by MohdFaisalAliKhan-Cedcoss** [comment]
Fixed and pushed

**Comment by MohdFaisalAliKhan-Cedcoss** [comment]
https://www.loom.com/share/526b0c4409dd4f478b771a0cc32a82d4
