### ISSUE TITLE
code error in plugin after activating the plugin

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#31]
os: window10
wp version: 5.8
wc version: 5.6.0
version: 1.4.3-opt
path: order bump and setting
description: code error occurs in plugin after activating the plugin
![code in plugin2021 09 04-11_44_31](https://user-images.githubusercontent.com/86113814/132084977-0ae79a0b-4c28-41bf-bd2d-150d1354fe20.png)

**Comment by ced-ashutoshv** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
solved
