### ISSUE TITLE
can not scroll wordpress dashboard

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#32]
os: window10
wp version: 5.8
wc version: 5.6.0
version:1.4.3-opt
description: after activating the plugin the dashboard of wp get fix to one place and can't scroll for other options,
![wordpress dashboard 2021 09 04-11_51_04](https://user-images.githubusercontent.com/86113814/132085106-0f1bc370-aaaa-4921-ac50-2d6946884996.png)

**Comment by ced-ashutoshv** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
solved
