### ISSUE TITLE
shape of product offer box change on click 

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#33]
os: window10
wp version: 5.8
wc version: 5.6.0
version:1.4.6-opt
path: save order bump
description: when we click on product offer, then the size of the box get change.
https://www.awesomescreenshot.com/video/5101955?key=a7f761e478d24d5d2015a6d4d8416987

**Comment by shivshukla1236** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
solved
