### ISSUE TITLE
discount text box not get disable when 'no discount' select

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#34]
os: window10
wp version:5.8
wc version: 5.6.0
version:1.4.3-opt
path: save order bump>offer price/discount
description: when we select no discount option, then discount text not get disable
![no discount 2021 09 04-12_19_17](https://user-images.githubusercontent.com/86113814/132085733-45c28b44-f071-4614-9ec6-96aa6806bedf.png)

**Comment by ced-ashutoshv** [comment]
We have left in enabled. Not an issue.

**Comment by prateek-cedcoss** [comment]
ok sir
