### ISSUE TITLE
code written after offer preview

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#35]
os:window10
wp version: 5.8
wc version: 5.6.0
version:1.4.3-opt
path: save order bump>offer preview
description: code written after the offer preview 
![code after preview -2021 09 04-12_25_25](https://user-images.githubusercontent.com/86113814/132085869-5c95d1b0-279b-4590-bc8d-d5991fa6e64c.png)
![image](https://user-images.githubusercontent.com/86113814/132087825-a08a038b-77fb-4a31-9925-e33597232914.png)

**Comment by ced-ashutoshv** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
solved
