### ISSUE TITLE
no validation in offer discount

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#37]
os: window10
wp version: 5.8
wc version: 5.6.0
version: 1.4.3-opt
path: save order bump> discount offe
description: no validation in offer discount, has it accept negative value or characters
![image](https://user-images.githubusercontent.com/86113814/132088820-5accd6ad-fe74-4045-b9fc-23c376e5e0d8.png)

![image](https://user-images.githubusercontent.com/86113814/132088848-ebffa45e-9913-408e-a034-402db03d3def.png)

**Comment by ced-ashutoshv** [comment]
fixed
