### ISSUE TITLE
no space between discount type and discount value in responsive

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#39]
os: window10
wp version: 5.8
wc version: 5.6.0
version: 1.4.3
path: save order bump
description: no space between discount type box and discount vale box
![text box -2021 09 04-13_33_36](https://user-images.githubusercontent.com/86113814/132087679-7eb882bb-94c3-4d75-a073-e4a906b372b8.png)

**Comment by shivshukla1236** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
solved
