### ISSUE TITLE
When we add target product and that target product as offer product

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/upsell-order-bump-offer-for-woocommerce#4]
Bug name:when target product is also offer product then there is error
Area Path: frontend>my account page
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:-When we remove target product from the order and the offer applied in the that offer product is added into card with its own original price 
Now if that offer product is also a target product of itself then when we apply offer into it then price of the order is increase but the quantity is not
![screenshot-192 168 1 184-2019 09 05-13_04_26](https://user-images.githubusercontent.com/48902379/64410425-a30afc00-d0a8-11e9-97b7-7c73c9944507.png)

**Comment by ced-ashutoshv** [comment]
fixed
