### ISSUE TITLE
name of the target product and offer product overlap other section

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#40]
os: window10
wp version: 5.8
wc version: 5.6.0
version: 1.4.3
path: order bump list
description: when the name of any product is big then that name overlap the other sections.
![name overlap -2021 09 04-13_49_40](https://user-images.githubusercontent.com/86113814/132088082-c5de221a-8ac8-4151-8c4f-60ab3790132f.png)

**Comment by ced-ashutoshv** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
solved
