### ISSUE TITLE
regular price and sale price are line-through

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#41]
os: window10
wp version: 5.8
wc version: 5.6.0
version: 1.4.3-opt
path: global setting
description: sale price and regular price are line-through in price offer format
![sale and regular price 2021 09 04-13_59_22](https://user-images.githubusercontent.com/86113814/132088378-a3bfc38c-c38b-461d-af18-05633f328f63.png)

**Comment by ced-ashutoshv** [comment]
Yes they are made line through just like and example replica.

**Comment by prateek-cedcoss** [comment]
ok sir, solved
