### ISSUE TITLE
office price/discount is not applicable on subscription variable product

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#43]
os: window10
wp version: 5.8
wc version: 5.6.0
version: 1.4.3-opt
path: save order bump
description: when we select discount% or fix price is applicable on subscription variable product
![variable subs2021 09 08-12_54_12](https://user-images.githubusercontent.com/86113814/132466364-668b3b89-3eaf-4cc2-9dcd-f0d9bf0068c8.png)

**Comment by ced-ashutoshv** [comment]
for parent product woocommerce shows a price range not a specific discount carrier.

**Comment by prateek-cedcoss** [comment]
ok sir got it.
