### ISSUE TITLE
issue with the count of offer price. watch video

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#44]
os: window10
wp:5.8
wc: 5.6.0
version: 1.4.3-opt
path: save order bump
description: when we change the value of the price offer 45, save the bump then it save as 44 and when we set 55, then it save as 54. 
https://www.awesomescreenshot.com/video/5143525?key=aa16079ed6655692e36178ecad8386a0

**Comment by ced-ashutoshv** [comment]
[screencast-nimbus-capture-2021.09.08-15_59_58.webm.zip](https://github.com/Makewebbetter/upsell-order-bump-offer-for-woocommerce/files/7128129/screencast-nimbus-capture-2021.09.08-15_59_58.webm.zip)


working fine

**Comment by prateek-cedcoss** [comment]
fix
