### ISSUE TITLE
QA/phpcs issue

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#48]
QA file:
https://docs.google.com/document/d/1DrgB0TF744T8zHwl7WA4ne8vKI7YoBEtnAfJEEIT4MQ/edit?usp=sharing

phpcs file:
[upsell-order-bump-offer-for-woocommerce-txt.txt](https://github.com/Makewebbetter/upsell-order-bump-offer-for-woocommerce/files/7162020/upsell-order-bump-offer-for-woocommerce-txt.txt)

plugin: 
[upsell-order-bump-offer-for-woocommerce.zip](https://github.com/Makewebbetter/upsell-order-bump-offer-for-woocommerce/files/7162023/upsell-order-bump-offer-for-woocommerce.zip)

**Comment by ced-ashutoshv** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
fix
