### ISSUE TITLE
box size of offer price/discount box is too large

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#51]
os: window11
wp: 5.8.1
wc: 5.8.0
version: 2.0.0
path: save order bump
description: size of the discount price box is too large.
![image](https://user-images.githubusercontent.com/86113814/139007782-f64623ae-f409-42ef-be29-21074c0a95d3.png)

**Comment by ced-ashutoshv** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
fix
