### ISSUE TITLE
offer bump is not working when offer product is set to gift product

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#52]
os: window11
wp: 5.8.1
wc: 5.8.0
ugc version: 2.2.0
version: 2.0.0
path: checkout page
description: when we set ulta gift cart product as a target product, then while accepting bump offer it does not accepting the offer product.

**Comment by ahmadabbas-cedcoss** [comment]
issue fixed

**Comment by prateek-cedcoss** [comment]
fix
