### ISSUE TITLE
issue with role base pricing

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#56]
os: window11
wp: 5.8.1
wc: 5.8.0
version: 2.0.0
description: it does not work with role base pricing as i show ahmad in my desktop.
![role base 2](https://user-images.githubusercontent.com/86113814/139388378-6d8a92e0-b59c-43c6-b367-cfb7934b9aea.png)
![role base 3](https://user-images.githubusercontent.com/86113814/139388383-b924f10f-d7c2-4555-953c-61abc9259613.png)
![rolebase1](https://user-images.githubusercontent.com/86113814/139388386-0af4c968-a817-44d7-92f7-8a44af301217.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue fixed

**Comment by prateek-cedcoss** [comment]
fix
