### ISSUE TITLE
php notice while activating gift card plugin

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#57]
os: window11
wp: 5.8.1
wc: 5.8.0
ugcwc version: 2.2.0
description: getting php notice on cart and checkout page after activating ultimate gift card for wc plugin.
https://www.loom.com/share/4c932d545b1b40808e1cff28cf964506

![screenshot-localhost_10040-2021 10 29-15_44_33](https://user-images.githubusercontent.com/86113814/139419006-59abf29e-c28a-4acd-bc44-4ccee557635e.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue fixed

**Comment by prateek-cedcoss** [comment]
fix
