### ISSUE TITLE
when role base plugin is active php notice occur in save order bump while apply discount % in offer price

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#58]
os: window11
wp: 5.8.1
wc: 5.8.0
version: 2.0.0
path: save order bump
description: when pro plugin and role base plugins is activate and in role base admin is enable with 50% in bean.  we set offer price in discount%, then php notice occurs in save order bump.
https://www.loom.com/share/e9a7c013378e42bc96d80c271acff6cf

![php notice by role base](https://user-images.githubusercontent.com/86113814/139528637-b65a0b34-e733-4f9a-be78-32b63250f8df.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue fixed

**Comment by prateek-cedcoss** [comment]
fix
