### ISSUE TITLE
issue with the pricing on 'no discount' when role base plugin activate

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#59]
os: window11
wp: 5.8.1
wc: 5.8.0
version: 2.0.0
path: save order bump
description: 
condition: role > admin beanie 50% off
when we select beanie in target product it show wrong amount after we apply no discount.
![no discount](https://user-images.githubusercontent.com/86113814/139528804-51ca47ea-6b23-4b19-a8bb-e8ee27400b66.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue solved

**Comment by prateek-cedcoss** [comment]
fix

**Comment by prateek-cedcoss** [comment]
still same issue not slove

**Comment by ahmadabbas-cedcoss** [comment]
issue fixed

**Comment by prateek-cedcoss** [comment]
fix
