### ISSUE TITLE
issue with gift cart meta form

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#60]
os: window11
wp: 5.8.1
wc: 5.8.0
version: 2.0.0
path: checkout page
description; when we fill meta from of gift cart that set in offer product, then in thank you page meta form fill information get repeated it self.
https://www.loom.com/share/6c03a29918a54a27b24379ab24a7aaf6

**Comment by ahmadabbas-cedcoss** [comment]
3 is from gift card and 3 is from upsell order bump unsetting any of them may result in loss of data

**Comment by prateek-cedcoss** [comment]
okay
