### ISSUE TITLE
issue while making payment through stipe of subscription product in bump

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#61]
os: window11
wp: 5.81
wc: 5.8.0
version: 2.0.0
path: checkout page
description: while purchasing product or subscription from order bump through stripe, then it show.
1: target product: polo    offer product: single
![stripe](https://user-images.githubusercontent.com/86113814/139530581-1f2a9e14-a10e-465d-b749-ba0fafbc205b.png)

2.target product: album     offer product: subscription product
![stripe 2](https://user-images.githubusercontent.com/86113814/139530799-cf1e2992-039c-49a2-8de5-6757735025c9.png)

3. normal product without bump offer
![stripe 3](https://user-images.githubusercontent.com/86113814/139530918-eeb7a0d4-2de7-4fc6-8ccd-d55be94b33fe.png)

**Comment by ahmadabbas-cedcoss** [comment]
try buying subscription product via stripe and let me know if the issue exist

**Comment by prateek-cedcoss** [comment]
fix
