### ISSUE TITLE
issue with the price of bump in item list when discount % is select

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#66]
os: window11
wp: 5.8.1
wc: 5.8.0
version:2.0.0
path:check out page item list
description: condition target product> beanie offer product> beanie discount type: discount% 50% off
while adding the bump in the item list then price is different.
![order bump](https://user-images.githubusercontent.com/86113814/139673182-08fa673b-7d39-4168-ba8c-f48dc3c8c1bc.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue fixed

**Comment by prateek-cedcoss** [comment]
fix
