### ISSUE TITLE
issue with the bump when target product is gift card and offer product is album

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#68]
os: window11
wp: 5.8.1
wc: 5.8.0
version: 2.0.0
path: checkout page
description: ultimate gift card plugin activate. when we set gift product as a target product and album as a offer product, then in site when we select bump it does not added to the item list. and getting php notice if we click on cart tab.
checkout page:
![cart](https://user-images.githubusercontent.com/86113814/139829938-3c91a5e1-e7ea-4268-9419-bf572e7f6827.png)

cart tab:
![gift cart](https://user-images.githubusercontent.com/86113814/139829691-d656af4d-7176-46cc-b601-09377c12bd62.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue fixed

**Comment by prateek-cedcoss** [comment]
fix
