### ISSUE TITLE
QA and phpcs issue

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#69]
QA file:
https://docs.google.com/document/d/18NW0cOCjHPZVVREZiil1PR-Tw0ma076G-NRU05rDKq8/edit?usp=sharing

phpcs file:
[upsell-order-bump-offer-for-woocommerce-xml.zip](https://github.com/Makewebbetter/upsell-order-bump-offer-for-woocommerce/files/7460337/upsell-order-bump-offer-for-woocommerce-xml.zip)

**Comment by ahmadabbas-cedcoss** [comment]
issues fixed phpcs errors of reporting folder need not to be corrected and role based plugin text domain is used at some places

**Comment by prateek-cedcoss** [comment]
fix
