### ISSUE TITLE
When we deactivate the pro plugin then all offer is empty

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/upsell-order-bump-offer-for-woocommerce#7]
Description:-when we deactivate the pro plugin the all offer made by the org and pro plugin are all empty ,when we click on the edit button but it's shown in order bump list
![screenshot-192 168 1 184-2019 11 08-11_09_04](https://user-images.githubusercontent.com/48902379/68452466-975ac380-0218-11ea-8632-bee422a6ea86.png)

**Comment by ced-ashutoshv** [comment]
> fixed
