### ISSUE TITLE
getting php notice on save order bump 

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#73]
os: window11
wp:5.8.2
wc: 5.9.0
version: 2.0.1
path: save order bump
description: when we set target product and offer product, the php notice occurs in the save order bump page.
![php notice](https://user-images.githubusercontent.com/86113814/142802156-b0e8ab76-fdbe-449d-a022-370c59aa6c21.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue solved

**Comment by prateek-cedcoss** [comment]
fix
