### ISSUE TITLE
issue with the input of Priority of the Order Bump

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#74]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.1
path: save order bump
description: already 9999 value is filled. 
![priority value](https://user-images.githubusercontent.com/86113814/142804407-14baba59-c45a-4886-af56-163b438ca7f2.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue solved

**Comment by prateek-cedcoss** [comment]
fix
