### ISSUE TITLE
getting php notice in checkout page 

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#75]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.1
path: checkout page
description: getting php notice while placing an order.
![php front end](https://user-images.githubusercontent.com/86113814/142805386-a3b1b96b-bc3e-4022-88e8-7381f7ed7338.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue solved

**Comment by prateek-cedcoss** [comment]
fix
