### ISSUE TITLE
Select roles to exclude is not working

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#76]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.1
path: save order bump
description: not able to search any role like guest, customer in Select roles to exclude section.
![role base](https://user-images.githubusercontent.com/86113814/142806051-c0592f17-e195-41ac-a693-c958cfdbee6d.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue solved

**Comment by prateek-cedcoss** [comment]
still not working.
https://www.loom.com/share/5acf13cd488f46af9834271252a3adf2

**Comment by ced-ashutoshv** [comment]
fixed

**Comment by prateek-cedcoss** [comment]
fix
