### ISSUE TITLE
data is not getting delete after uninstalling the plugin 

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#77]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.1
path: global setting
description: when we enabling 'Enable Delete all data on uninstall' and uninstalled the plugin but after reinstalling and activating the, plugin getting previous save bump offer.

**Comment by ahmadabbas-cedcoss** [comment]
issue solved

**Comment by prateek-cedcoss** [comment]
fix
