### ISSUE TITLE
issue with the clone feature on org

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#78]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.1
path: order bump list
description: as there is a bump limit on org, but due to clone feature we can create more then one bump in org.

**Comment by ahmadabbas-cedcoss** [comment]
issue solved

**Comment by prateek-cedcoss** [comment]
fix
