### ISSUE TITLE
issue with the product permalink target

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#79]
os: window11
wp: 5.8.2
wc: 5.9.0
path: checkout page
description: when we select product permalink target to 'parent frame' or 'full window' it work same as 'open in same frame'.

**Comment by ahmadabbas-cedcoss** [comment]
issue solved

**Comment by prateek-cedcoss** [comment]
fix as these two option are removed
