### ISSUE TITLE
when we select checkout method using plugin "aerocheckout"(org)

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/upsell-order-bump-offer-for-woocommerce#8]
Description:-When we use checkout method "aero checkout" then offer product show quantity field and when we increase the quantity of offer product then it increase the offer quantity with same offer price
![screenshot-192 168 1 184-2019 11 08-10_46_27](https://user-images.githubusercontent.com/48902379/68452716-64fd9600-0219-11ea-8244-69d7f1bea6fd.png)

**Comment by ced-ashutoshv** [comment]
> Fixed
