### ISSUE TITLE
QA/phpcs issue

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#81]
QA file: 
https://docs.google.com/document/d/1kc8joAJME00uVNECQMyo_AXpWueTGj4W6_py0IUlDUs/edit?usp=sharing

phpcs file:
[upsell-order-bump-offer-for-woocommerce-xml.zip](https://github.com/Makewebbetter/upsell-order-bump-offer-for-woocommerce/files/7616274/upsell-order-bump-offer-for-woocommerce-xml.zip)

file:
[upsell-order-bump-offer-for-woocommerce.zip](https://github.com/Makewebbetter/upsell-order-bump-offer-for-woocommerce/files/7617016/upsell-order-bump-offer-for-woocommerce.zip)

**Comment by ahmadabbas-cedcoss** [comment]
issues fixed and commented
ignore reporting phpcs issues

**Comment by prateek-cedcoss** [comment]
fix
