### ISSUE TITLE
disable priority of the order nump text box

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#84]
os: window11
wp: 5.8.2
wc: 6.0.0
version: 2.0.2
path: save order bump
description: is this feature is for pro plugin but we can able to write on it, it as to be disable ,

actual:
![image](https://user-images.githubusercontent.com/86113814/146721169-3e52b109-0166-45de-aa05-be8143934dff.png)

expected
![image](https://user-images.githubusercontent.com/86113814/146721063-cf1506c7-4346-4437-9a99-74a6e5f6069e.png)
not able to write anything in this box as it is for pro feature

**Comment by ahmadabbas-cedcoss** [comment]
issue solved

**Comment by prateek-cedcoss** [comment]
fix
